### ISSUE TITLE
Question about how to reset json-server data

### ISSUE THREAD

**Issue by jenschiavone** [bahmutov/json-server-reset#1]
I'm experimenting with using json-server to mock backend responses for Protractor testing. I would like to be able to reset the data after each test is run. I'm trying out json-server-reset, but do not quite understand how to get this part to work:

http POST :3000/reset todos:=[]

I have tried using Postman, and also in my typescript code using HttpClient.

Do you have any additional instructions you could provide? Can you show me how you would set it up in Postman?

I have tried with this URL: http://localhost:3000/reset

And I've tried these different bodies:

{"books": []}

books:[]

But I get either Internal Server Error or Bad Request errors. I do not think this is a bug or anything, I just need additional assistance on how to properly make this call.

Thanks for any assistance you can provide.

**Comment by bahmutov** [comment]
in Postman - have you set it to `application/json` request type? Also, a full working application that uses the reset is in this blog post https://www.cypress.io/blog/2017/11/28/testing-vue-web-application-with-vuex-data-store-and-rest-backend/

But the request should be a JSON POST with body `{"books": []}`, also can you trie using httpie just to see if my examples work?

**Comment by bahmutov** [comment]
I don’t know then what is going on, you would need to debug the code by adding console log statements. Maybe the route is incorrect or something else is different.

**Comment by jenschiavone** [comment]
Yeah, I removed the route entirely in case that was the issue, but I found the behavior to be the same. These are just direct calls with Postman, so no code to debug, unless you mean debugging the jsonServerReset function itself?

**Comment by bahmutov** [comment]
Yes debugging the json reset code (which is a very simple middleware). Is it working with httpie? Also have you tried using Cypress instead of Protractor?

**Comment by jenschiavone** [comment]
Thanks very much for responding to my questions. I have accomplished what I was trying to do in another manner. We can close this issue.
